<div class="w-[1440px] h-[3230px] relative bg-[#020202]  overflow-hidden">
    <div class="w-[1440px] h-[1024px] left-0 top-0 absolute bg-black/0"></div>
    <img class="w-[1440px] h-[961px] left-0 top-0 absolute" src="https://via.placeholder.com/1440x961" />
    <div class="w-[1440px] h-[961px] left-0 top-0 absolute bg-gradient-to-b from-black via-[#010101] to-[#070707]"></div>
    <div class="w-7 h-[0px] left-[237px] top-[62px] absolute origin-top-left rotate-90 border-4 border-white"></div>
    <div class="w-[131px] h-[66px] left-[89px] top-[47px] absolute">
        <div class="w-[131px] h-[66px] left-0 top-0 absolute text-white text-2xl font-bold font-['Inknut Antiqua'] leading-7 tracking-wide">Turkey<br/>Tourists</div>
        <div class="w-5 h-5 left-[102px] top-[12px] absolute text-[#befc13] text-[40px] font-bold font-['Inknut Antiqua']">.</div>
    </div>
    <div class="w-5 h-5 left-[446px] top-[420px] absolute text-[#befc13] text-[40px] font-bold font-['Inknut Antiqua']">.</div>
    <div class="left-[645px] top-[64px] absolute justify-start items-center gap-[29px] inline-flex">
        <div class="w-[47px] h-5 justify-center items-center flex">
            <div class="text-white text-[17px] font-bold font-['Inria Serif']">Home</div>
        </div>
        <div class="w-[99px] h-5 justify-center items-center flex">
            <div class="text-white text-[17px] font-bold font-['Inria Serif']">Destinations</div>
        </div>
        <div class="w-[89px] h-5 justify-center items-center flex">
            <div class="text-white text-[17px] font-bold font-['Inria Serif']">Attractions </div>
        </div>
        <div class="w-[73px] h-5 justify-center items-center flex">
            <div class="text-[#befc13] text-[17px] font-bold font-['Inria Serif']">Activities </div>
        </div>
        <div class="w-[95px] h-5 justify-center items-center flex">
            <div class="text-white text-[17px] font-bold font-['Inria Serif']">Restaurants </div>
        </div>
        <div class="w-[136px] h-5 justify-center items-center flex">
            <div class="text-white text-[17px] font-bold font-['Inria Serif']">Accommodations</div>
        </div>
    </div>
    <div class="w-[529px] h-[207px] left-[172px] top-[244px] absolute text-[#befc13] text-[50px] font-bold font-['Inknut Antiqua'] leading-[69px] tracking-[3px]">Explore Turkey's Top Adventure</div>
    <div class="w-[116px] h-1.5 left-[172px] top-[469px] absolute">
        <div class="w-[116px] h-1.5 left-0 top-0 absolute bg-[#befc13] rounded-md blur-[30px]"></div>
        <div class="w-[116px] h-1.5 left-0 top-0 absolute bg-[#befc13] rounded-md shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]"></div>
    </div>
    <div class="h-[98px] left-[626px] top-[863px] absolute">
        <img class="w-9 h-9 left-[75px] top-[32px] absolute" src="https://via.placeholder.com/36x36" />
        <img class="w-6 h-6 left-[105px] top-[74px] absolute origin-top-left rotate-90" src="https://via.placeholder.com/24x24" />
        <div class="w-[187px] h-[27px] left-0 top-0 absolute text-center text-[#befc13] text-base font-bold font-['Inknut Antiqua'] leading-snug">DISCOVER MORE</div>
    </div>
    <div class="w-[1288px] h-[437px] left-[75px] top-[1130px] absolute justify-start items-center gap-[30px] inline-flex">
        <div class="w-[1288px] h-[437px] justify-start items-center gap-[30px] flex">
            <div class="w-[399.97px] h-[445px] relative">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                    <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                    <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                        <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                    </div>
                </div>
                <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Paragliding in Ölüdeniz</div>
                <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Fethiye</div>
                <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Paragliding</div>
                <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                    <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
                </div>
            </div>
            <div class="w-[399.97px] h-[445px] relative">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                    <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                    <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                        <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                    </div>
                </div>
                <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Hot Air Ballooning </div>
                <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Cappadocia</div>
                <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Ballooning</div>
                <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                    <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
                </div>
            </div>
            <div class="w-[399.97px] h-[445px] relative">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                    <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px] shadow-[0px_4px_4px_0px_rgba(72,72,72,0.25)]"></div>
                    <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                        <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                    </div>
                </div>
                <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Trekking in Lycian Way</div>
                <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Antalya</div>
                <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Trekking</div>
                <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                    <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
                </div>
            </div>
            <div class="w-[399.97px] h-[445px] relative">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                    <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                    <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                        <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                    </div>
                </div>
                <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">ATV Rides</div>
                <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Cappadocia</div>
                <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">ATV Riding</div>
                <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                    <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
                </div>
            </div>
            <div class="w-[399.97px] h-[445px] relative">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                    <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                    <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                        <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                    </div>
                </div>
                <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">White-water Rafting</div>
                <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Antalya</div>
                <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Rafting</div>
                <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                    <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
                </div>
            </div>
            <div class="w-[399.97px] h-[445px] relative">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                    <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                    <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                        <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                    </div>
                </div>
                <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Skiing in Uludağ</div>
                <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Bursa</div>
                <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Skiing</div>
                <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                    <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
                </div>
            </div>
            <div class="w-[399.97px] h-[445px] relative">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                    <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                    <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                        <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                    </div>
                </div>
                <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Diving</div>
                <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Kaş</div>
                <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Diving</div>
                <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
                <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                    <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
                </div>
            </div>
        </div>
    </div>
    <div class="w-[1288px] h-[437px] left-[77px] top-[1770px] absolute justify-start items-center gap-[30px] inline-flex">
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px]  overflow-hidden">
                    <img class="w-[400px] h-[333px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px]" src="https://via.placeholder.com/400x333" />
                    <img class="w-[456px] h-[342px] left-[-28px] top-[-4px] absolute" src="https://via.placeholder.com/456x342" />
                    <img class="w-[499px] h-[333px] left-[-74px] top-0 absolute" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Kaputaş Beach</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Kaş</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Beach</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Patara Beach</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Antalya</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Beach</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px]  overflow-hidden">
                    <img class="w-[400px] h-[333px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px]" src="https://via.placeholder.com/400x333" />
                    <img class="w-[456px] h-[342px] left-[-28px] top-[-4px] absolute" src="https://via.placeholder.com/456x342" />
                    <img class="w-[499px] h-[333px] left-[-74px] top-0 absolute" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Blue Lagoon (Ölüdeniz)</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Fethiye</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Beach</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Kabak Beach</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Fethiye</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Beach</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
    </div>
    <div class="w-[1288px] h-[437px] left-[79px] top-[2410px] absolute justify-start items-center gap-[30px] inline-flex">
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Paragliding in Ölüdeniz</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Fethiye</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Paragliding</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Hot Air Ballooning </div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Cappadocia</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Ballooning</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px] shadow-[0px_4px_4px_0px_rgba(72,72,72,0.25)]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Trekking in Lycian Way</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Antalya</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Trekking</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">ATV Rides</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Cappadocia</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">ATV Riding</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">White-water Rafting</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Antalya</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Rafting</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Skiing in Uludağ</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Bursa</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Skiing</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
        <div class="w-[399.97px] h-[445px] relative">
            <div class="w-[399.97px] h-[445px] left-0 top-0 absolute">
                <div class="w-[399.97px] h-[445px] left-0 top-0 absolute bg-black rounded-[45px]"></div>
                <div class="w-[399.97px] h-[333.09px] pb-[0.09px] left-0 top-0 absolute rounded-tl-[45px] rounded-tr-[45px] justify-start items-center inline-flex overflow-hidden">
                    <img class="w-[499px] h-[333px]" src="https://via.placeholder.com/499x333" />
                </div>
            </div>
            <div class="w-[347px] h-10 left-[21px] top-[345px] absolute text-white text-3xl font-bold font-['Inria Serif']">Diving</div>
            <div class="w-[125px] h-[29px] left-[40px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Kaş</div>
            <div class="w-[143px] h-[29px] left-[189px] top-[398px] absolute text-[#befc13] text-xl font-bold font-['Inria Serif']">Diving</div>
            <div class="w-2 h-1.5 left-[25px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-2 h-1.5 left-[173px] top-[366px] absolute text-[#befc13] text-[50px] font-bold font-['Inria Serif']">.</div>
            <div class="w-[46.40px] h-[46.40px] left-[321px] top-[29px] absolute justify-center items-center inline-flex">
                <img class="w-[46.40px] h-[46.40px]" src="https://via.placeholder.com/46x46" />
            </div>
        </div>
    </div>
    <div class="w-[1303px] h-56 left-[69px] top-[2983px] absolute">
        <div class="w-[231px] h-[167px] left-[531px] top-0 absolute">
            <div class="h-12 p-2.5 left-0 top-[33px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">destinations</div>
            </div>
            <div class="h-12 p-2.5 left-0 top-[76px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Attractions</div>
            </div>
            <div class="h-12 p-2.5 left-0 top-[119px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Activities</div>
            </div>
            <div class="w-[221px] h-[33px] left-[10px] top-0 absolute text-[#befc13] text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Main Pages</div>
        </div>
        <div class="w-[231px] h-[167px] left-[812px] top-0 absolute">
            <div class="h-12 p-2.5 left-0 top-[33px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Home</div>
            </div>
            <div class="h-12 p-2.5 left-0 top-[76px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Profile</div>
            </div>
            <div class="h-12 p-2.5 left-0 top-[119px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Wish List</div>
            </div>
            <div class="w-[221px] h-[33px] left-[10px] top-0 absolute text-[#befc13] text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Pages</div>
        </div>
        <div class="w-[231px] h-[124px] left-[1072px] top-0 absolute">
            <div class="h-12 p-2.5 left-0 top-[33px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Restaurants</div>
            </div>
            <div class="h-12 p-2.5 left-0 top-[76px] absolute justify-center items-center gap-2.5 inline-flex">
                <div class="text-white text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Accommodations</div>
            </div>
            <div class="w-[221px] h-[33px] left-[10px] top-0 absolute text-[#befc13] text-xl font-bold font-['Inknut Antiqua'] leading-7 tracking-tight">Pages</div>
        </div>
        <div class="w-[347px] h-[91.40px] left-0 top-[106px] absolute">
            <div class="w-[343.20px] h-[41.40px] left-0 top-[50px] absolute">
                <div class="w-[343.20px] h-[41.40px] left-0 top-0 absolute bg-[#d9d9d9]/20 rounded-lg border border-[#bbff00]"></div>
                <div class="w-[97.20px] h-[41.40px] left-[246px] top-0 absolute bg-[#befc13]/80 rounded-lg border border-[#befc13]"></div>
                <div class="w-[90px] h-[16.80px] left-[249.60px] top-[13px] absolute text-center text-black text-xs font-bold font-['Inknut Antiqua'] leading-none tracking-tight">Subscribe</div>
            </div>
            <div class="w-[342px] h-[25px] left-[5px] top-[24px] absolute"><span class="text-[#befc13] text-[11px] font-bold font-['Inknut Antiqua'] leading-[15.18px] tracking-tight">Get</span><span class="text-white text-[11px] font-bold font-['Inknut Antiqua'] leading-[15.18px] tracking-tight"> the latest updates in Türkiye!</span></div>
            <div class="w-[342px] h-[25px] left-[5px] top-0 absolute"><span class="text-[#befc13] text-[15px] font-bold font-['Inknut Antiqua'] leading-tight tracking-tight">Newsletter</span><span class="text-white text-[15px] font-bold font-['Inknut Antiqua'] leading-tight tracking-tight">:</span></div>
        </div>
        <div class="w-[131px] h-[66px] left-0 top-[20px] absolute">
            <div class="w-[131px] h-[66px] left-0 top-0 absolute text-white text-2xl font-bold font-['Inknut Antiqua'] leading-7 tracking-wide">Turkey<br/>Tourists</div>
            <div class="w-5 h-5 left-[102px] top-[12px] absolute text-[#befc13] text-[40px] font-bold font-['Inknut Antiqua']">.</div>
        </div>
        <div class="left-[540px] top-[209px] absolute text-center text-[#befc13] text-[11px] font-bold font-['Inknut Antiqua'] leading-[15.18px] tracking-tight">Copyright ©️ 2024 All Rights Reserved </div>
        <div class="w-[218.40px] h-[16.80px] left-[12.60px] top-[169px] absolute text-center text-white/40 text-xs font-bold font-['Inknut Antiqua'] leading-none tracking-tight">Write your Email</div>
    </div>
    <img class="w-[58px] h-[58px] left-[1361px] top-[45px] absolute rounded-full" src="https://via.placeholder.com/58x58" />
    <div class="w-[204px] h-8 pr-[53px] left-[277px] top-[64px] absolute justify-start items-start gap-3 inline-flex">
        <img class="w-8 h-8" src="https://via.placeholder.com/32x32" />
        <div class="w-[107px] h-[24.50px] relative">
            <div class="w-[107px] h-5 left-0 top-0 absolute text-white/0 text-[1px] font-bold font-['Inria Sans'] tracking-tight">Search</div>
        </div>
    </div>
    <div class="left-[96px] top-[1018px] absolute justify-start items-end gap-[15px] inline-flex">
        <div class="w-[1118px] h-[76px]"><span class="text-[#befc13] text-[50px] font-bold font-['Inknut Antiqua'] leading-[69px] tracking-wide">Must Try </span><span class="text-white text-[50px] font-bold font-['Inknut Antiqua'] leading-[69px] tracking-wide">Adventures</span></div>
        <div class="w-[60px] h-[60px] relative">
            <div class="w-[60px] h-[60px] left-[60px] top-0 absolute origin-top-left rotate-180 rounded-full border border-white"></div>
        </div>
        <div class="w-[60px] h-[60px] relative">
            <div class="w-[60px] h-[60px] left-0 top-0 absolute rounded-full border border-white"></div>
        </div>
    </div>
    <div class="left-[98px] top-[1658px] absolute justify-start items-center gap-3 inline-flex">
        <div class="w-[1118px] h-[76px]"><span class="text-[#befc13] text-[50px] font-bold font-['Inknut Antiqua'] leading-[69px] tracking-wide">Nature </span><span class="text-white text-[50px] font-bold font-['Inknut Antiqua'] leading-[69px] tracking-wide">Attractions</span></div>
        <div class="w-[60px] h-[60px] relative">
            <div class="w-[60px] h-[60px] left-[60px] top-0 absolute origin-top-left rotate-180 rounded-full border border-white"></div>
        </div>
        <div class="w-[60px] h-[60px] relative">
            <div class="w-[60px] h-[60px] left-0 top-0 absolute rounded-full border border-white"></div>
        </div>
    </div>
    <div class="left-[100px] top-[2298px] absolute justify-start items-center gap-[11px] inline-flex">
        <div class="w-[1118px] h-[76px]"><span class="text-[#befc13] text-[50px] font-bold font-['Inknut Antiqua'] leading-[69px] tracking-wide">Nature </span><span class="text-white text-[50px] font-bold font-['Inknut Antiqua'] leading-[69px] tracking-wide">Attractions</span></div>
        <div class="w-[60px] h-[60px] relative">
            <div class="w-[60px] h-[60px] left-[60px] top-0 absolute origin-top-left rotate-180 rounded-full border border-white"></div>
        </div>
        <div class="w-[60px] h-[60px] relative">
            <div class="w-[60px] h-[60px] left-0 top-0 absolute rounded-full border border-white"></div>
        </div>
    </div>
</div>